### ISSUE TITLE
Item NBT differences

### ISSUE THREAD

**Issue by Myretix** [altaiiiir/Viner#15] opened 2023-11-01 02:54 UTC
**Minecraft 1.20.1**
Disclaimer: I am using a modpack, and this bug may be a compatibility issue(?). None of the other mods seem to cause this bug on their own.

Mod causes certain blocks to have an NBT tag, meaning like-blocks will not stack:
https://github.com/altaiiiir/Viner/assets/149551003/745e583e-09bd-4412-92c3-05ba36ec422c

Difficult to properly reproduce, as it just seems to happen at random. Vein-mining doesn't _100%_ cause this issue, it just seems to happen on occasion. Mining blocks with said NBT tag removes it, allowing it to stack regularly:
https://github.com/altaiiiir/Viner/assets/149551003/324b1188-71fa-48fb-83b4-41b51384d819

Edit: Occasionally, saplings dropped from vein-mined leaves have this NBT issue. Seems to be the easiest way to recreate bug.

**Comment by TheJaysH** [comment] 2023-11-01 19:27
Hi @Myretix 

What version of the mod are you using?

**Comment by Myretix** [comment] 2023-11-07 05:04
Version 2.0.0 for Forge 1.20.1

**Comment by altaiiiir** [comment] 2024-04-08 03:42
I believe this was resolved in a previous update. Please feel free to submit another bug report if the issue is still happening. Thanks for helping make this project better for the community!

**Comment by altaiiiir** [comment] 2024-04-08 03:42
I believe this was resolved in a previous update. Please feel free to submit another bug report if the issue is still happening. Thanks for helping make this project better for the community!

**Closed by altaiiiir** 2024-04-08 03:42 UTC
Labels: bug
